# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Blog
title_top: Technical Documentation
email: karthick87@github.com
description: > # this means to ignore newlines until "baseurl:"
  A space to express some thoughts and opinions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://karthick87.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/  # Make sure this format is followed everywhere. Comment section will break if we change this
twitter_username: karthick87
github_username:  karthick87

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
